### ISSUE TITLE
Telegram shows message as call from "Unknown" after update – iPhone 6

### ISSUE THREAD

**Issue by hamza200411** [TelegramMessenger/Telegram-iOS#1761]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
After updating Telegram to the latest version, I found a bug on my iPhone 6 with iOS 12.5.7. Every time I get a message from anyone, it shows up as a call from "Unknown" in my call log. Even if I delete and reinstall the Telegram app, the issue still exists.

### Expected Behavior
When someone sends me a message, I should just get a notification or see the message — not a call.

### Actual Behavior
Every message triggers a fake Telegram call from the sender, but the call is labeled as "Unknown." It is not a real call, just a bug.

### Steps to Reproduce
1. Open Telegram on iPhone 6 with iOS 12.5.7
2. Receive a message from someone
3. Check recent calls — it shows as a Telegram call from "Unknown"
4. Reinstalling the app does not fix it

### Screenshots and Videos 
![Image](https://github.com/user-attachments/assets/28f64681-6b3b-4743-b39e-2d62119c841b)

### Environment
**Device:** `iPhone 6`

**iOS version**: `12.5.7`

**App version:** `Latest version (11.11)`

**Comment by povar81** [comment]
Having the same issue.
Device: iPhone 7
iOS version: 14.3

**Comment by Tommy-Dorian** [comment]
Have this one on IPhone 7...
Is this bug because of telegram update?

**Comment by hamza200411** [comment]
> Have this one on IPhone 7... Is this bug because of telegram update?

Yes, same here. It started after the update.

**Comment by hamza200411** [comment]
> Have this one on IPhone 7... Is this bug because of telegram update?

Yes, same here. It started after the update.

**Comment by ali-fareed** [comment]
Fixed in 11.11.1.

**Comment by hamza200411** [comment]
> Fixed in 11.11.1.

The Issue still exists.

**Comment by NadiiaRomaniuk** [comment]
Yes, the issue is there still

**Comment by varnie** [comment]
Yes, the issue is there still

**Comment by euphorical** [comment]
This issue is still present. I've updated to the latest version of Telegram, and yet I still keep getting random "unknown" Telegram calls. 

I am on an iPhone 11 by the way.

**Comment by hamza200411** [comment]
> This issue is still present. I've updated to the latest version of Telegram, and yet I still keep getting random "unknown" Telegram calls. 
> 
> I am on an iPhone 11 by the way. 

The issue has been resolved in 11.11.2
