### ISSUE TITLE
Telegram Requires Full Contact Access, Ignoring iOS Limited Access Settings

### ISSUE THREAD

**Issue by BeingAl** [TelegramMessenger/Telegram-iOS#1774]
### Description
On iOS, there’s a feature that lets you give limited access instead of full access to certain things. This also applies to contacts.

I have two different Telegram accounts, and in each one, I only want specific contacts to be synced—not all of them.
So in the settings, I set Telegram’s access to contacts as "Limited" and choose only the contacts I want to sync with Telegram.

But this doesn’t work. None of the selected contacts actually sync, and Telegram doesn’t recognize any of my numbers.
It only works if I give it Full Access to my contacts.

But it should work with Limited Access and only sync the contacts I selected—just like WhatsApp does.
WhatsApp supports this perfectly: it only syncs and shows the contacts you selected under Limited Access.

### Expected Behavior
It should sync and recognize the contacts that were selected under Limited Access—not just completely disable the contact syncing feature.

### Actual Behavior
It completely disables the contact syncing feature until you give it full access again.
This behavior goes against user privacy because it forces the user to grant full access.

### Steps to Reproduce
1. Go to the iOS settings, then into Telegram’s settings.
2. Under Permissions, you tap on Contacts.
3. Then you set it to Limited Access and choose some specific contacts you want.

### Environment
**Device:** `iPhone 14`

**iOS version**: `18.5`

**App version:** `11.11.2`

**Comment by GoddessOfSwords** [comment]
#1638

**Comment by BeingAl** [comment]
This bug was fixed in **version(11.12)**, which was published 7–8 hours ago.
There’s just one remaining issue: when you click the Manage button to select your desired contacts, after making your selection and tapping Done, the Telegram app appears to freeze.
You need to minimize the app and reopen it for things to work normally again.

However, this isn’t a functional freeze or a crash — the app is still running in the background, but none of the buttons respond until you minimize and bring it back up.

I’ll continue checking to make sure everything else is working properly.

**Comment by axl84** [comment]
Not fixed in 11.12

**Comment by BeingAl** [comment]
These are the screenshots of the version I mentioned, where if you set Telegram’s access to “Limited” in iOS settings, you can view them from the Contacts tab in Telegram.

But there are a few bugs. I described one of them earlier — the freezing issue — and I’ll include a screenshot of that.

The red areas show the gap between the Telegram app and the edges of the phone screen. This happens when you exit the "Manage Contacts" section and tap “Done.” The layout becomes broken and doesn’t fix itself unless you minimize and reopen the app, or fully close and relaunch it.

There’s another bug as well: Telegram provides the option to choose which of the contacts (you’ve granted access to) should be synced. Personally, I think this feature isn’t necessary, but they’ve included it anyway.

However, this part doesn’t actually work. No matter which contact you select in the "Manage Contacts" section in Telegram, it ends up syncing all the contacts you granted access to in iOS settings. So effectively, that feature has no impact.

![Image](https://github.com/user-attachments/assets/6d408154-5f99-4f75-9e76-0047b279a2b0)
![Image](https://github.com/user-attachments/assets/3b76b5c7-a03d-4414-8bf2-ee4c16907c24)
![Image](https://github.com/user-attachments/assets/d6e8bed6-72be-49c1-a0ec-39c40bb74e6b)

**Comment by axl84** [comment]
![Image](https://github.com/user-attachments/assets/9b2ba4df-f4f8-4fe4-819f-4b8f01514479)
![Image](https://github.com/user-attachments/assets/a9213bb7-b9eb-4bbc-890d-41f85da450f0)
![Image](https://github.com/user-attachments/assets/3b56676b-ac78-49f6-bf50-54fe019f6fa0)

At least App Store version (11.12) not fixed

**Comment by BeingAl** [comment]
Telegram has a place for reporting bugs and features, but it's so crowded that I feel anything posted there might not get noticed. The link is:
[https://bugs.telegram.org/](https://bugs.telegram.org)

That's why I also reported this bug through their support page, and you can do the same here:
[https://telegram.org/support](https://telegram.org/support)

**Comment by GoddessOfSwords** [comment]
There is already a bug report on bugs.telegram.org, and you can support it by upvoting. If this issue concerns you, please click 'Like' on the bug report page (link below). Your support can help bring the issue to the developers' attention and potentially speed up its resolution.

Bug report link: 
https://bugs.telegram.org/c/46192
